// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGnlIezSpmHfpdXLW1nxhIQ7pe7EtnJ04',
    appId: '1:737388705630:web:8ac41cb55e6f9adaeb01cf',
    messagingSenderId: '737388705630',
    projectId: 'dri-learn',
    authDomain: 'dri-learn.firebaseapp.com',
    storageBucket: 'dri-learn.appspot.com',
    measurementId: 'G-WV16EB2JXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwdiA2IZ6mtCG4T0LZiQY7lK4znaHxbtM',
    appId: '1:737388705630:android:40d1bfe0615db1aceb01cf',
    messagingSenderId: '737388705630',
    projectId: 'dri-learn',
    storageBucket: 'dri-learn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoJhI4rm62uBbtDFtW_Fg5XndWJapDE54',
    appId: '1:737388705630:ios:b1a4b3d184ae73e2eb01cf',
    messagingSenderId: '737388705630',
    projectId: 'dri-learn',
    storageBucket: 'dri-learn.appspot.com',
    iosBundleId: 'com.example.mePassDriveTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoJhI4rm62uBbtDFtW_Fg5XndWJapDE54',
    appId: '1:737388705630:ios:b1a4b3d184ae73e2eb01cf',
    messagingSenderId: '737388705630',
    projectId: 'dri-learn',
    storageBucket: 'dri-learn.appspot.com',
    iosBundleId: 'com.example.mePassDriveTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGnlIezSpmHfpdXLW1nxhIQ7pe7EtnJ04',
    appId: '1:737388705630:web:b51ad7f92df99fe6eb01cf',
    messagingSenderId: '737388705630',
    projectId: 'dri-learn',
    authDomain: 'dri-learn.firebaseapp.com',
    storageBucket: 'dri-learn.appspot.com',
    measurementId: 'G-CKQXJZNHQZ',
  );

}