// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7LL9dr29gHOBJOJr4i8filGUWpJH4wxs',
    appId: '1:910080401209:web:7482a1dc4b4f7c374112e8',
    messagingSenderId: '910080401209',
    projectId: 'drilearn',
    authDomain: 'drilearn.firebaseapp.com',
    storageBucket: 'drilearn.appspot.com',
    measurementId: 'G-7XWCDR64VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLRJfobLKBTL5FPYxofMfxQz5iKlPZOp8',
    appId: '1:910080401209:android:a78504c96ae13efb4112e8',
    messagingSenderId: '910080401209',
    projectId: 'drilearn',
    storageBucket: 'drilearn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuTabhmrwTVLQRG359MXko0mqHciYrhVk',
    appId: '1:910080401209:ios:b14749f15620ed7c4112e8',
    messagingSenderId: '910080401209',
    projectId: 'drilearn',
    storageBucket: 'drilearn.appspot.com',
    iosBundleId: 'com.example.driLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuTabhmrwTVLQRG359MXko0mqHciYrhVk',
    appId: '1:910080401209:ios:b14749f15620ed7c4112e8',
    messagingSenderId: '910080401209',
    projectId: 'drilearn',
    storageBucket: 'drilearn.appspot.com',
    iosBundleId: 'com.example.driLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7LL9dr29gHOBJOJr4i8filGUWpJH4wxs',
    appId: '1:910080401209:web:ec75bbef6ea144734112e8',
    messagingSenderId: '910080401209',
    projectId: 'drilearn',
    authDomain: 'drilearn.firebaseapp.com',
    storageBucket: 'drilearn.appspot.com',
    measurementId: 'G-9M2QFMWP6H',
  );

}